id: P010419
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 20:48:51.808907
source_metadata:
  id: bdr:W1PD152291
  title: དཔལ་ལྡན་ས་སྐྱ་པའི་གསུང་རབ་གྲགས་ཆེན་བཅོ་བརྒྱད།
  author: ''
  volumes:
    1f00cef01be746e3980a9831909ef726:
      image_group_id: I2PD18407
      title: ''
      volume_number: 1
      total_pages: 546
      base_file: v001.txt
    98917c230b5a468e9f2c9ad8e8a742f9:
      image_group_id: I2PD18408
      title: ''
      volume_number: 2
      total_pages: 574
      base_file: v002.txt
    cd3a71a27e364ffcb7995ec3a7093b20:
      image_group_id: I2PD18409
      title: ''
      volume_number: 3
      total_pages: 298
      base_file: v003.txt
    6b1e0cba3552495f82bb99cf37e8dbd2:
      image_group_id: I2PD18410
      title: ''
      volume_number: 4
      total_pages: 334
      base_file: v004.txt
    e51952b3d59f4520868d8ad8772680a9:
      image_group_id: I2PD18411
      title: ''
      volume_number: 5
      total_pages: 662
      base_file: v005.txt
    f6f2c77ad61946af8160d38248a090b1:
      image_group_id: I2PD18412
      title: ''
      volume_number: 6
      total_pages: 508
      base_file: v006.txt
    3d1b4b6576734c78baaeee29ab9e496b:
      image_group_id: I2PD18413
      title: ''
      volume_number: 7
      total_pages: 676
      base_file: v007.txt
    e6ab383c4ae94bd2b4e70e8a01544a60:
      image_group_id: I2PD18414
      title: ''
      volume_number: 8
      total_pages: 804
      base_file: v008.txt
    96af996a6e734ed587f05a32c13f38ef:
      image_group_id: I2PD18415
      title: ''
      volume_number: 9
      total_pages: 586
      base_file: v009.txt
    fdabb8ac73b648a3920cfd016d31ac01:
      image_group_id: I2PD18416
      title: ''
      volume_number: 10
      total_pages: 306
      base_file: v010.txt
    cccd9844ed4940079d2a4e91260812db:
      image_group_id: I2PD18417
      title: ''
      volume_number: 11
      total_pages: 338
      base_file: v011.txt
    a49833d4d4fa4603b37167e42dd4f21e:
      image_group_id: I2PD18418
      title: ''
      volume_number: 12
      total_pages: 348
      base_file: v012.txt
    e967ee6bd8934c668887d5aebd8247c9:
      image_group_id: I2PD18419
      title: ''
      volume_number: 13
      total_pages: 232
      base_file: v013.txt
    800efae235244cf3be001b8e82c1e14c:
      image_group_id: I2PD18420
      title: ''
      volume_number: 14
      total_pages: 350
      base_file: v014.txt
    8d341c3102a54d20b17c01aa4779a141:
      image_group_id: I2PD18421
      title: ''
      volume_number: 15
      total_pages: 334
      base_file: v015.txt
    f55635457f804474a8e3ad70439bf623:
      image_group_id: I2PD18422
      title: ''
      volume_number: 16
      total_pages: 316
      base_file: v016.txt
    99bc1f16a4834772958847f311ce816d:
      image_group_id: I2PD18423
      title: ''
      volume_number: 17
      total_pages: 554
      base_file: v017.txt
    47642776292148a2afad4cee91a27fee:
      image_group_id: I2PD18424
      title: ''
      volume_number: 18
      total_pages: 498
      base_file: v018.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
